name: Build and Release AUR Package

on:
  workflow_dispatch:
    inputs:
      link:
        description: "Exact name of the AUR package nothing extra"
        required: true
        default: " "

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB.TOKEN}}
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upgrade and install Packages
        run: |
          set -e 
          sudo apt-get update -y && sudo apt-get upgrade -y 
          sudo apt-get install wget curl -y 
          wget ${{github.event.inputs.link}}
      - name: Check if Pkgs Exist
        run: |
          if ls  *.zip 1> /dev/null 2>&1; then
            echo "CHECK_FILE_IS_OK=true" >> $GITHUB_ENV &&
            echo "Found them"
          else
            echo "PKG directory is empty."
          fi

      - name: Upload to Release
        if: env.CHECK_FILE_IS_OK == 'true'
        uses: softprops/action-gh-release@v2
        with:
          files: ./*.zip
          name: files
          tag_name: ${{github.run_id}}
          body: test
